project_name: ssh-agent-inject
before:
  hooks:
  - go mod download
  - go generate ./...
env:
- CGO_ENABLED=0
builds:
- id: windows
  goos:
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
  - -H windowsgui
- id: unix
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
archives:
- id: windows
  builds:
  - windows
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
- id: unix
  builds:
  - unix
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
